#!/bin/sh
# setup rke2 server and install rancher
PUBLIC_IP=$(curl ifconfig.io)

export INSTALL_RKE2_VERSION="v1.21.3-rc2+rke2r2"

curl -sfL https://get.rke2.io | sh -
mkdir -p /etc/rancher/rke2
cat > /etc/rancher/rke2/config.yaml <<EOF
write-kubeconfig-mode: "0640"
tls-san:
  - "${PUBLIC_IP}" 
  - "${PUBLIC_IP}.nip.io"
cni: "calico"
EOF

systemctl enable rke2-server
systemctl start rke2-server

cat >> /etc/profile <<EOF
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
PATH="$PATH:/var/lib/rancher/rke2/bin"
alias k=kubectl
EOF

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
PATH="$PATH:/var/lib/rancher/rke2/bin"

while [ ! -f /var/lib/rancher/rke2/bin/kubectl ] ; do
    echo "kubectl missing from PATH, sleeping for 5 seconds"
    sleep 5
done

mkdir -p /var/lib/rancher/rke2/server/manifests
cat >> /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml <<EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
EOF

curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm fetch rancher-stable/rancher
/var/lib/rancher/rke2/bin/kubectl create namespace cattle-system
/var/lib/rancher/rke2/bin/kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml
# Create the namespace for cert-manager
/var/lib/rancher/rke2/bin/kubectl create namespace cert-manager 

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4

# wait for pods to be running
sleep 5

helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --version 2.5.9 \
  --set hostname="${PUBLIC_IP}".nip.io \
  --set antiAffinity="required" 

touch /tmp/finished-user-data
